### ISSUE TITLE
20 decimal hours? Why not 10?

### ISSUE THREAD

**Issue by mindey** [kmturley/decimal-time#1]
Hi there, :) That all makes sense, except for 20 hours, Why not 10 hours? Here's my take on similar project, in Python: **[detime](https://github.com/mindey/detime)**.

**Comment by kmturley** [comment]
Thanks for taking a look at my project!

I picked all numbers as the closest to existing numbers but base ten.

24 hours > 20
12 months > 10

It makes people feel more comfortable as it's more similar to what they currently use.

I have not tested for leap years, I don't have any tests in fact. So that's a great idea.

I'll take a look at your library to see the similarities.
I realized I had a few changes in progress which weren't pushed to the demo. So will get those updated too

**Comment by mindey** [comment]
I see. So, this is due to am/pm mindset, but having 10 hours also divides into before/after: before 5 and after 5.

Btw., I noticed some rounding functions in your code ([here](https://github.com/kmturley/decimal-time/blob/master/decimal-time.js#L61-L81)). Ideally, it should not use any rounding, and be deterministic. So, yeah, recommend to take a look at my implementation. Conveniently, Python has the `calendar` package, that allows to check the leap years, which is important for months. I chose to add the extra day in leap year at the ending (last) month, and chose to alternate other months as `[36, 37,...]` starting from the smaller number (`36`). In general, it would be good to arrive at consensus decimal time eventually. It could be an RFC proposal to standards, if it doesn't exist yet. I wonder, if it exists.

**Comment by kmturley** [comment]
I have just pushed my updated demo, which has a visual comparison of Decimal and Gregorian clocks / calendars. 

I can consider adopting your suggestions, they are logical and make sense. It's amazing that we both came to very similar conclusions!

My code was a prototype and there are some use-cases it doesn't cover:
- Timezones
- Leap years

I think the best way to align would be to create some test cases/data. We could use them to test edge-cases and assure that both our libraries are deterministic and output the same result?

**Comment by mindey** [comment]
// I think the best way to align would be to create some test cases/data. 

That's a very good point. We could also try to agree upon some axioms. I've described my axioms [here](https://github.com/mindey/detime#axioms).

The edge cases to me, appeared to be the handling of negative years, like -- what is the date of 1969-12-31 ? In my case, it is -0001-10-37, however 1970-01-01 equates to 0000-01-01. What is in your case? In case of leap years, I'm adding one day to the last month.

Your'e making good point about timezones support. The offsets would be fractional, and it's interesting to handle them. I'll think of test-cases file. Here's a [video comment](https://wiki.mindey.com/shared/shots/77367d3c34e6abe77726df0af-decimal-time-comment.mp4).

**Comment by kmturley** [comment]
I've merged the 10 hour day change, and removed the rounding functions.

I installed your library and compared the two. You're right, the days are off by one when I compare them side-by-side:
<img width="1022" alt="Screen Shot 2021-09-21 at 3 39 10 AM" src="https://user-images.githubusercontent.com/1710493/134156768-178f9584-45a5-43c1-8ee9-9929efec2084.png">

I'm not sure if the difference is due to:

- Timezones
- Logic errors
- something else

Will look into it with the new typescript version which will have tests!

**Comment by mindey** [comment]
Traditionally, when people write 01 day of the month, and we want to compute the number of seconds passed from the beginning of the month, we have to treat 01 as 0. I think the problem might come from that distinction.

// Will look into it with the new typescript version which will have tests!

That will be great, typescript is useful for it. Will look forward to it. My first test [here](https://github.com/mindey/detime/blob/master/detime/test_fmap.py), as I have added the possibility to compute the traditional date back from the decimal date using a separate function (rather than mathematical inverse), and the requirements is for them to match.

**Comment by kmturley** [comment]
I have added my tests here:
https://github.com/kmturley/decimal-time/blob/gh-pages/tests/index.test.ts

Updated demo here:
https://kimturley.co.uk/decimal-time/index.html

Let me know what you think
